apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-operator
  project: default
  source:
    # chart: istio-operator
    helm:
    parameters:
      - name: enableCRDTemplates
        value: 'true'
    repoURL: https://github.com/istio/istio/
    targetRevision: 1.7.0
    path: manifests/charts/istio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
