apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gitops-istio
  region: us-west-2
  version: "1.20"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 5
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 5
