argo-cd:
  installCRDs: false # Required for Helm v3
  global:
    image:
      tag: v2.0.3 # To get latest version, default is 1.7.x
  dex:
    enabled: false # Used for external auth providers
  server:
    extraArgs:
      - --insecure # Local k8s without TLS
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm